### ISSUE TITLE
Continuous Model Training for LR Model

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#178]
Distributed NN supports continuous training: If existing model in model output folder, a new training job will start from the existing model and not from random model weights.

This feature is very useful for modelers to continue training in one break point.

For LR d-training, better if we have such feature.

isContinuous in ModelConfig.json#train is for such feature, by default is false. Which means if LR and isContinuous=true, such feature will be enabled.

Solution for this feature is to read existing model in the first iteration, if no existing model, starting from random weights. Be careful, if model is changed for example, a new column is added, even enable continuous model training, should start from initial random weights because of in-consistent models.

**Comment by zhang7575** [comment]
I am working on this
