### ISSUE TITLE
Drop variables in train step

### ISSUE THREAD

**Issue by m4rkl1u** [ShifuML/shifu#20]
shifu drop variables in normalize step, but it's not very friendly for modeler, because they love to change columnconfig in any time and train them, so I would like to propose new steps:

1. in normalize, shifu should normalize all variables, and keep all into normalized file.
2. in train, shifu check the columnconfig and drop those variables aren't "final select".

once shifu work like this, modeler could update columnconfig in anytime and skip the normalize step.

**Comment by zhangpengshan** [comment]
Done in 0.2.4 relase
