### ISSUE TITLE
Unittest failed

### ISSUE THREAD

**Issue by m4rkl1u** [ShifuML/shifu#331]
Some unittes fail because of Scorer's toScore scale disable

Failed tests:   testBelowScore(ml.shifu.shifu.udf.EvalScoreUDFTest)
  testExec(ml.shifu.shifu.udf.EvalScoreUDFTest): 
  testExecScale(ml.shifu.shifu.udf.EvalScoreUDFTest):
  testGetSchema(ml.shifu.shifu.udf.EvalScoreUDFTest): 
  testExec(ml.shifu.shifu.udf.FullScoreUDFTest):

**Comment by huzza** [comment]
It is caused by we change score type from int to double. I will fix soon

**Comment by huzza** [comment]
fixed
