### ISSUE TITLE
candidateColumnNameFile cannot work

### ISSUE THREAD

**Issue by jirachikai** [ShifuML/shifu#414]
In varsel step, there is a config to state candidateColumnNameFile. The original idea is to run varsel from variables in this file, but it seems that it cannot work correct.

**Comment by zhangpengshan** [comment]
The issue is only in sensitivity analysis variable selection, Thanks a lot Wenkai. This is a bug and the fix is in: 
https://github.com/ShifuML/shifu/commit/6b4a33e01eca9bb2e8e0cc2a6182c5c513b22176#diff-6a6bde2f1b5f3e7b3adc72f8efc930c9L736

**Comment by zhangpengshan** [comment]
Fixed in develop branch
