### ISSUE TITLE
typo on line 327

### ISSUE THREAD

**Issue by Siyi** [ShifuML/shifu#508]
https://github.com/ShifuML/shifu/blob/5d6c496bb943d082eb6de997e4f8f999b52fcea7/src/main/resources/store/ModelConfigMeta.json#L327

**Comment by zhangpengshan** [comment]
Thanks Siyi. Fixed it in develop branch: https://github.com/ShifuML/shifu/commit/2d3e8859cc11be3911be362faa4e793c4fc6bc0c
