### ISSUE TITLE
ShifuML run test failed for version 0.11.3 and 0.11.4

### ISSUE THREAD

**Issue by ddkongbb** [ShifuML/shifu#522]
Some files in src\test\resources are missing so that the compile run for version 0.11.3 and 0.11.4 would be failed without skiptest. 
Copy src\test\resources\*.* from version 0.11.2 would solve the problem and allow the compile run successfully.

**Comment by zhangpengshan** [comment]
Thanks @ddkongbb, we will fix it soon in develop branch.

**Comment by zhangpengshan** [comment]
new develop branch UT has been fixed and all runs well, please check. I closed such issue if you still see i failures. Please reopen it
