### ISSUE TITLE
Add Distributed LR implementation Based on Guagua

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#56]

**Comment by zhang7575** [comment]
I'll work on this

**Comment by zhangpengshan** [comment]
Done in develop-0.2.7 branch
Features: L1 & L2 Regularization, whole process except exporting to PMML.
Later performance comparasion with NN will be post

**Comment by zhangpengshan** [comment]
![image](https://cloud.githubusercontent.com/assets/7368102/9702738/f6c9be3e-549d-11e5-9d12-1d3377983307.png)
