### ISSUE TITLE
Percentile for better understand variables

### ISSUE THREAD

**Issue by m4rkl1u** [ShifuML/shifu#6]
Percentile is a very helpful indicator for statisticians, it could tell if the data is skew, or a normalize distribution.

A good implementation for percentile is datafu by linkedin, http://datafu.incubator.apache.org/docs/datafu/1.2.0/datafu/pig/stats/Quantile.html

Just wondering would we add this feature for further release?

**Comment by zhangpengshan** [comment]
Done in 0.2.4 release, another issue for EqualPositive is added: https://github.com/ShifuML/shifu/issues/65
