### ISSUE TITLE
Set the Hadoop parallel number automatically

### ISSUE THREAD

**Issue by huzza** [ShifuML/shifu#64]
1. Set the default value of Hadoop parallel number to be empty;
2. If the Hadoop parallel number is empty, calculate the best Hadoop parallel number.

The best hadoop parallel number should be between (1, total-column-number]. And it also should consider the data size.

**Comment by zhangpengshan** [comment]
Add:
SET pig.exec.reducers.max 999;
SET pig.exec.reducers.bytes.per.reducer 536870912;

replace default parallel setting for all pig scripts

Done in develop branch

**Comment by zhangpengshan** [comment]
For some jobs in stats, parallel should use column parallel settings.

**Comment by zhangpengshan** [comment]
Done but still some issues with big data in hadoop 2.2.1
