### ISSUE TITLE
FindBugs Issues

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#70]
Hi All Devs,

Please use findbugs to check your code and try to fix all default findbugs errors and warnings asap.

Thanks,
Zhang, Pengshan(David)

**Comment by zhengxiaobin** [comment]
I'll work on this :)

**Comment by zhengxiaobin** [comment]
I use findbugs find that ModelBasicConf and ModelConfig define equals() function without override hashCode() . I think it's better to override it. Is it ok to use the automatically generated hashcode() by eclipse ?

**Comment by zhangpengshan** [comment]
Thanks, Xiaobin. Please check your PR CI results.

**Comment by zhangpengshan** [comment]
Thanks, Xiaobin. Already merge your PR to develop 0.2.5 branch.
