### ISSUE TITLE
NaN fall into the last bin

### ISSUE THREAD

**Issue by m4rkl1u** [ShifuML/shifu#717]
In this line to get the bin index 
https://github.com/ShifuML/shifu/blob/master/src/main/java/ml/shifu/shifu/core/Normalizer.java#L640

If the value is "NaN", it will give the last bin number https://github.com/ShifuML/shifu/blob/master/src/main/java/ml/shifu/shifu/util/BinUtils.java#L189
 
```
 public void test2() {
    List<Double> bins = Arrays.asList(Double.valueOf("-Infinity"),
    1.3540577379901267E-4, 3.4140840073655133E-4, 8.388314917856846E-4, 0.0015892474745600124, 0.003504418399376486, 0.013004966254920104);

    Double val = Double.valueOf("NaN");

    System.out.println(getBinIndex(bins, val));
  }
```

This suppose to be the last bin number

**Comment by zhangpengshan** [comment]
Good catch, Mark. WIP.

**Comment by zhangpengshan** [comment]
Done in develop branch.
