### ISSUE TITLE
Add convergence parameter to Shifu d-train

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#76]
To stop d-training iteration, so far max iteration number is used, better to provide  a convergence parameter then user can set both convergence and max iteration number together.

**Comment by asd7853** [comment]
I'm working on this issue.

**Comment by zhangpengshan** [comment]
Merge pull request from asd7853: https://github.com/ShifuML/shifu/pull/101

**Comment by zhangpengshan** [comment]
I just got the idea at that time I created this issue.

Not only to provide a threshold, but also error between this iteration and last iteration should be checked also. Let's think about it.

**Comment by zhengxiaobin** [comment]
Yes, sometimes people want the training process stop when the result nearly unchanged. I think this kind of end-up criteria will be useful.
